version: 1.0.{build}
image: Visual Studio 2017
#not published for vs2019
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: auSP7uJIC8Y5I0AW97f0ANIOLXxkszux38+nFJhry4PFvH1MBd1xfBFMcA30a8Z9  
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
before_build:
    - cmd: nuget restore AutoFindReplace.sln
    - dotnet tool install -g dotnet-sonarscanner
    - dotnet sonarscanner begin /key:"AutoFindReplace" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%my_encrypted_sonarqube_token%" /o:"gregtrevellick-github"
build:
    project: AutoFindReplace.sln
    verbosity: minimal
after_build:
     - dotnet sonarscanner end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true