// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoFindReplace
{
    static class Vsix
    {
        public const string Id = "0EAEA679-4BFB-4E54-B52B-A5F5FD1B523D";
        public const string Name = "AutoFindReplace";
        public const string Description = @"Automatically perform a find/replace action on individual file(s) within a specified project(s) upon opening a named solution. ";
        public const string Language = "en-US";
        public const string Version = "1.3.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "find, replace, automatic, text, change, controlF, controlH, ctlF, ctlH";
    }
}
